# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 11:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="IFC CODE MUST BE PUT IN FORMAT: 'ABHY0065001'. Up to 11 digits allowed.", regex='^[0-9A-Z]{11}')])),
                ('bank_branch', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(default='', max_length=512)),
                ('state', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('content', models.TextField(help_text='SMS content', verbose_name='content')),
                ('to', models.CharField(db_index=True, max_length=32, verbose_name='receiver')),
                ('failure_code', models.TextField(blank=True, default=None, null=True, verbose_name='failure code')),
                ('mid', models.TextField(blank=True, help_text='Message ID is used to track the delivery', null=True, verbose_name='Message ID')),
                ('operator', models.IntegerField(choices=[(0, 'Unknown'), (1, 'MGage')], default=0, verbose_name='Operator Used')),
            ],
            options={
                'verbose_name': 'SMS',
                'ordering': ('-modified_at',),
                'get_latest_by': 'modified_at',
                'verbose_name_plural': 'SMSes',
            },
        ),
        migrations.CreateModel(
            name='VerifiablePincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('pincode', models.ManyToManyField(to='external_api.Pincode', verbose_name='pincode')),
            ],
            options={
                'verbose_name': 'VerifiablePincode',
                'ordering': ('modified_at',),
                'get_latest_by': 'modified_at',
                'verbose_name_plural': 'VerifiablePincodes',
            },
        ),
    ]
