# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='micr_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
