# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 11:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('external_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='user id')),
                ('first_name', models.CharField(blank=True, default='', max_length=254, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=254, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, default='', max_length=254, verbose_name='last name')),
                ('username', models.CharField(max_length=254, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 12 digits allowed.", regex='[0-9]{10,12}')], verbose_name='phone_number')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='dob')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect it instead of deleting accounts.', verbose_name='active')),
                ('image', models.ImageField(blank=True, max_length=700, null=True, upload_to='profile/image/')),
                ('country_of_birth', models.CharField(blank=True, default='', max_length=254, verbose_name='country of birth')),
                ('nationality', models.CharField(blank=True, default='', max_length=254, verbose_name='nationality')),
                ('tax_status', models.CharField(blank=True, default='', help_text='Check whether user is tax payer in other country.', max_length=254, verbose_name='tax status')),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('phone_number_verified', models.BooleanField(default=False, verbose_name='phone number verification status')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verification status')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('identity_info_image', models.FileField(blank=True, max_length=700, null=True, upload_to='identity/image/')),
                ('marital_status', models.CharField(choices=[('1', 'Single'), ('2', 'Married')], default='', max_length=1)),
                ('is_investor_info', models.BooleanField(default=False, verbose_name='is investor info complete')),
                ('is_contact_info', models.BooleanField(default=False, verbose_name='is contact info complete')),
                ('is_identity_info', models.BooleanField(default=False, verbose_name='is identity info complete')),
                ('is_bank_info', models.BooleanField(default=False, verbose_name='is bank info complete')),
                ('is_nominee_info', models.BooleanField(default=False, verbose_name='is nominee info complete')),
                ('is_declaration', models.BooleanField(default=False, verbose_name='is declaration complete')),
                ('is_terms', models.BooleanField(default=False, verbose_name='is terms and conditions accepted')),
                ('process_choice', models.CharField(blank=True, choices=[('0', 'Completely paperless online process'), ('1', 'Print and courier yourself'), ('2', 'Doorstep representative')], default='', max_length=1)),
                ('mandate_status', models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Ongoing'), ('2', 'Completed')], default='0', max_length=1)),
                ('xsip_status', models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Ongoing'), ('2', 'Completed')], default='0', max_length=1)),
                ('signature', models.FileField(blank=True, max_length=700, null=True, upload_to='user/signature/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('finaskus_id', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('mandate_reg_no', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Mandate Registration Number')),
                ('bse_registered', models.BooleanField(default=False)),
                ('tiff_mailed', models.BooleanField(default=False)),
                ('tiff_accepted', models.BooleanField(default=False)),
                ('kyc_mailed', models.BooleanField(default=False)),
                ('kyc_accepted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', profiles.manager.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=2048, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=2048, null=True)),
                ('nearest_landmark', models.CharField(blank=True, max_length=2048, null=True)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_api.Pincode')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='appointment_date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='appointment_time')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Ongoing'), (2, 'Complete')], default=0)),
                ('address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_address', to='profiles.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('address_are_equal', models.BooleanField(default=False, help_text='Is communication and permanent address same')),
                ('address_proof_type', models.IntegerField(choices=[(1, 'Passport'), (2, 'Driving_License'), (3, 'Voter_ID_Card'), (4, 'Aadhaar_Card'), (5, 'Bank_Statement'), (6, 'Utility_Bill'), (7, 'Ration_Card')], default=None, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='phone_number')),
                ('front_image', models.FileField(blank=True, max_length=1023, null=True, upload_to='contact/address_proof/')),
                ('back_image', models.FileField(blank=True, max_length=1023, null=True, upload_to='identity/address_proof/')),
                ('communication_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_communication_address', to='profiles.Address')),
                ('permanent_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permanent_address', to='profiles.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('code', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('S', 'Savings'), ('C', 'Current')], max_length=1)),
                ('sip_check', models.BooleanField(default=False)),
                ('bank_cheque_image', models.FileField(blank=True, max_length=1023, null=True, upload_to='cheque/image/')),
                ('ifsc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='external_api.BankDetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('investor_status', models.CharField(default='Resident Individual', max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Pan number must be entered in the format:'AAAPL1234C'", regex='^([a-zA-Z]){5}([0-9]){4}([a-zA-Z]){1}')], verbose_name='Pan Number')),
                ('applicant_name', models.CharField(blank=True, max_length=512, null=True)),
                ('father_name', models.CharField(blank=True, max_length=512, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='dob')),
                ('income', models.CharField(blank=True, choices=[('1', '< 1 Lakh'), ('2', '1-5 Lakhs'), ('3', '5-10 Lakhs'), ('4', '10-25 Lakhs'), ('5', '25-100 Lakhs'), ('6', '> 100 Lakhs')], max_length=1, null=True)),
                ('political_exposure', models.CharField(blank=True, choices=[('1', 'Not applicable'), ('2', 'I am a PEP'), ('3', 'I am related to PEP')], max_length=1, null=True)),
                ('occupation_type', models.CharField(blank=True, choices=[('PRI', 'Private Sector Service'), ('PRO', 'Professional (Self-Employed)'), ('BUS', 'Business'), ('HOU', 'Housewife'), ('PUB', 'Public Sector Service'), ('GOV', 'Government Service'), ('RET', 'Retired'), ('FOR', 'Forex Dealer'), ('AGR', 'Agriculturist'), ('STU', 'Student'), ('OTH', 'Other (please specify)')], default=None, max_length=3, null=True)),
                ('occupation_specific', models.CharField(blank=True, max_length=512, null=True)),
                ('other_tax_payer', models.BooleanField(default=False, help_text='Do you pay tax in country other than India')),
                ('pan_image', models.FileField(blank=True, max_length=700, null=True, upload_to='investor_info/pan/image')),
                ('kra_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NomineeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name='nominee name')),
                ('nominee_dob', models.DateField(blank=True, null=True, verbose_name='dob')),
                ('guardian_name', models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name='guardian name')),
                ('relationship_with_investor', models.IntegerField(choices=[(1, 'Spouse'), (2, 'Parent'), (3, 'Offspring'), (4, 'Sibling'), (5, 'Other')], default=None, null=True)),
                ('nominee_absent', models.BooleanField(default=False, verbose_name='is nominee is absent')),
                ('address_are_equal', models.BooleanField(default=False, help_text='Is nominee address same as investor communication address')),
                ('nominee_signature', models.FileField(blank=True, max_length=700, null=True, upload_to='nominee/signature/')),
                ('nominee_address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominee_address', to='profiles.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationSMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('sms_code', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
