# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_aggregateportfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregateportfolio',
            options={'ordering': ['-total_xirr']},
        ),
    ]
