# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160509_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregateportfolio',
            name='total_xirr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
