# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160516_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='permanent_address_proof_type',
            field=models.IntegerField(choices=[(1, 'Passport'), (2, 'Driving_License'), (3, 'Voter_ID_Card'), (4, 'Aadhaar_Card'), (5, 'Bank_Statement'), (6, 'Utility_Bill'), (7, 'Ration_Card')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='permanent_back_image',
            field=models.FileField(blank=True, max_length=1023, null=True, upload_to='contact/permanent_address_proof/'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='permanent_front_image',
            field=models.FileField(blank=True, max_length=1023, null=True, upload_to='contact/permanent_address_proof/'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='back_image',
            field=models.FileField(blank=True, max_length=1023, null=True, upload_to='contact/address_proof/'),
        ),
    ]
