# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userchangedphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address_proof_type',
            field=models.IntegerField(choices=[(1, 'Passport'), (2, 'Driving_License'), (3, 'Voter_ID_Card'), (4, 'Aadhaar_Card'), (5, 'Bank_Statement'), (6, 'Utility_Bill'), (7, 'Ration_Card'), (8, 'Lease')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='permanent_address_proof_type',
            field=models.IntegerField(choices=[(1, 'Passport'), (2, 'Driving_License'), (3, 'Voter_ID_Card'), (4, 'Aadhaar_Card'), (5, 'Bank_Statement'), (6, 'Utility_Bill'), (7, 'Ration_Card'), (8, 'Lease')], default=None, null=True),
        ),
    ]
