# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20160601_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vault_locked',
            field=models.BooleanField(default=False),
        ),
    ]
