# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_user_vault_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vault_locked',
            field=models.BooleanField(default=False, help_text='Is vault locked?'),
        ),
    ]
