# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20160602_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_real_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_virtual_seen',
            field=models.BooleanField(default=False),
        ),
    ]
