# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20160607_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorbankdetails',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
    ]
