# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_user_rebuild_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='communication_address_type',
            field=models.IntegerField(choices=[(1, 'Residential'), (2, 'Business'), (3, 'Residential_Business'), (4, 'Registered_Office')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='investorinfo',
            name='country_of_birth',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='country of birth'),
        ),
        migrations.AddField(
            model_name='investorinfo',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='place of birth'),
        ),
    ]
