# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20161020_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_thumbnail',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to='profile/image/thumbnail'),
         ),
    ]
