# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0004_vendor'),
        ('profiles', '0016_auto_20161005_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('mandate_registered', models.BooleanField(default=False)),
                ('mandate_reg_no', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Mandate Registration Number')),
                ('mandate_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('mandate_start_date', models.DateField()),
                ('mandate_status', models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Ongoing'), ('2', 'Completed')], default='0', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='uservendor',
            name='mandate_reg_no',
        ),
        migrations.RemoveField(
            model_name='uservendor',
            name='mandate_registered',
        ),
        migrations.RemoveField(
            model_name='uservendor',
            name='mandate_status',
        ),
        migrations.AddField(
            model_name='userbankmandate',
            name='mandate_bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.InvestorBankDetails'),
        ),
        migrations.AddField(
            model_name='userbankmandate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbankmandate',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_mandate_vendor', to='external_api.Vendor'),
        ),
    ]
