# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_user_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='back_image_thumbnail',
            field=models.FileField(blank=True, max_length=1023, null=True, upload_to='contact/address_proof/thumbnail'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='front_image_thumbnail',
            field=models.FileField(blank=True, max_length=1023, null=True, upload_to='contact/address_proof/thumbnail'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='permanent_back_image_thumbnail',
            field=models.FileField(blank=True, max_length=1023, null=True, upload_to='contact/permanent_address_proof/thumbnail'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='permanent_front_image_thumbnail',
            field=models.FileField(blank=True, max_length=1023, null=True, upload_to='contact/permanent_address_proof/thumbnail'),
        ),
        migrations.AddField(
            model_name='investorbankdetails',
            name='bank_cheque_image_thumbnail',
            field=models.FileField(blank=True, max_length=1023, null=True, upload_to='cheque/image/thumbnail'),
        ),
        migrations.AddField(
            model_name='investorinfo',
            name='pan_image_thumbnail',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to='investor_info/pan/image/thumbnail'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_info_image_thumbnail',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to='identity/image/thumbnail'),
        ),
    ]
