# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20161019_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorinfo',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='investorinfo',
            name='mother_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        )
       
    ]
