# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundredeemitem',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
