# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fundredeemitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_id',
            field=models.CharField(max_length=50),
        ),
    ]
