# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fundredeemitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundredeemitem',
            name='redeem_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fundredeemitem',
            name='unit_redeemed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
