# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160506_0611'),
        ('core', '0003_auto_20160505_1134'),
    ]

    operations = [
    ]
