# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundredeemitem',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is verified'),
        ),
    ]
