# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160509_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundredeemitem',
            name='unit',
        ),
    ]
