# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fundredeemitem_is_verified'),
        ('core', '0006_remove_fundredeemitem_unit'),
    ]

    operations = [
    ]
