# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 06:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='fund',
            name='sip_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
