# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 06:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20160513_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FundHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='folionumber',
            name='fund_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FundHouse'),
        ),
        migrations.AddField(
            model_name='folionumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FundHouse'),
        ),
        migrations.AlterUniqueTogether(
            name='folionumber',
            unique_together=set([('user', 'fund_house')]),
        ),
    ]
