# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160519_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundorderitem',
            name='unit_alloted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundredeemitem',
            name='unit_redeemed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
