# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160520_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtfunds',
            name='average_credit_quality',
            field=models.CharField(max_length=10),
        ),
    ]
