# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160520_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
