# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160524_1042'),
        ('core', '0013_auto_20160523_1302'),
    ]

    operations = [
    ]
