# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160530_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundorderitem',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='is cancelled'),
        ),
        migrations.AddField(
            model_name='fundredeemitem',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='is cancelled'),
        ),
    ]
