# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160530_0731'),
    ]

    operations = [
    ]
