# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160531_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
    ]
