# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_portfolio_is_deleted'),
        ('core', '0017_auto_20160530_1101'),
    ]

    operations = [
    ]
