# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_name',
        ),
    ]
