# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160607_0723'),
        ('core', '0020_portfolioperformance_xirr'),
    ]

    operations = [
    ]
