# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundredeemitem',
            name='is_all_units_redeemed',
            field=models.BooleanField(default=False, verbose_name='Redeem all units ?'),
        ),
        migrations.AddField(
            model_name='redeemdetail',
            name='is_all_units_redeemed',
            field=models.BooleanField(default=False, verbose_name='Redeem all units ?'),
        ),
    ]
