# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mostpopularfundsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='minimum_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='minimum_withdrawal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
