# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20160617_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheddata',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
