# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20160617_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemdetail',
            name='invested_redeem_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
