# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fundredeemitem_invested_redeem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundorderitem',
            name='sip_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='sip_reminder_sent'),
        ),
    ]
