# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 03:17
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fundorderitem_sip_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundorderitem',
            name='is_future_sip_cancelled',
            field=models.BooleanField(default=False, verbose_name='is future sip cancelled'),
        ),
    ]
