# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 08:56
from __future__ import unicode_literals

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0004_vendor'),
        ('core', '0030_auto_20161005_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundVendorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('sip_dates', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('neft_scheme_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Scheme Code when investment amount is below Rs. 2 lakhs ')),
                ('rtgs_scheme_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Scheme Code when investment amount is above Rs. 2 lakhs ')),
            ],
        ),
        migrations.AddField(
            model_name='fundvendorinfo',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fund'),
        ),
        migrations.AddField(
            model_name='fundvendorinfo',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_api.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='fundvendorinfo',
            unique_together=set([('fund', 'vendor')]),
        ),
    ]
