# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20161010_0856'),
        ('core', '0030_auto_20161005_0317'),
    ]

    operations = [
    ]
