# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 05:17
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20161020_0958'),
        ('core', '0032_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='bank_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_mandate', to='profiles.UserBankMandate'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='image_url',
            field=profiles.models.S3PrivateImageField(blank=True, max_length=700, null=True, upload_to=core.models.unique_fund_image),
        ),
    ]
