# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 04:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_auto_20161021_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('category', models.CharField(choices=[('R', 'Retirement'), ('T', 'Tax Saving'), ('BP', 'Buy Property'), ('E', 'Higher Education'), ('W', 'Save for Wedding'), ('O', 'Other Events'), ('I', 'Invest')], max_length=254, verbose_name='Category')),
                ('name', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('asset_allocation', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='goal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Goal'),
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together=set([('user', 'category', 'portfolio', 'name')]),
        ),
    ]
