# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20161116_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('R', 'Retirement'), ('T', 'Tax Saving'), ('BP', 'Buy Property'), ('E', 'Higher Education'), ('W', 'Save for Wedding'), ('O', 'Other Events'), ('I', 'Invest'), ('L', 'liquid')], max_length=254, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_for',
            field=models.CharField(choices=[('A', 'Assess'), ('P', 'Plan'), ('R', 'Retirement'), ('T', 'Tax Saving'), ('BP', 'Buy Property'), ('E', 'Higher Education'), ('W', 'Save for Wedding'), ('O', 'Other Events'), ('I', 'Invest'), ('L', 'Liquid')], max_length=254, verbose_name='category'),
        ),
    ]
