# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20161121_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='liquid_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
