# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 18:12
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_portfolio_liquid_percentage1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundorderitem',
            name='folio_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fundorderitem',
            name='units_redeemed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fundredeemitem',
            name='folio_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fundredeemitem',
            name='grouped_redeem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GroupedRedeemDetail'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='goal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Goal'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='sip_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='folionumber',
            unique_together=set([('user', 'fund_house', 'folio_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioitem',
            unique_together=set([('portfolio', 'fund', 'goal')]),
        ),
    ]
