# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 05:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20161124_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='planassestallocation',
            name='automobile_allocation',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planassestallocation',
            name='jewellery_allocation',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planassestallocation',
            name='liquid_allocation',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planassestallocation',
            name='vacation_allocation',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_for',
            field=models.CharField(choices=[('A', 'Assess'), ('P', 'Plan'), ('R', 'Retirement'), ('T', 'Tax Saving'), ('BP', 'Buy Property'), ('E', 'Higher Education'), ('W', 'Save for Wedding'), ('O', 'Other Events'), ('I', 'Invest'), ('L', 'Liquid'), ('AM', 'Auto Mobile'), ('V', 'Vacation'), ('J', 'Jewellery')], max_length=254, verbose_name='category'),
        ),
    ]
