# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20161126_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='folionumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 1, 10, 40, 22, 732698), verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folionumber',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 1, 10, 40, 41, 260301), verbose_name='Modified at'),
            preserve_default=False,
        ),
    ]
