# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20161129_0507'),
        ('core', '0037_auto_20161126_1812'),
    ]

    operations = [
    ]
