# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20161201_1040'),
        ('core', '0039_merge'),
    ]

    operations = [
    ]
