# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_time',
            field=models.DateTimeField(blank=True, default=None, max_length=100, null=True, verbose_name='Transaction Time'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='additional_info_2',
            field=models.CharField(default='10382', max_length=100, verbose_name='Folio Number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='additional_info_5',
            field=models.CharField(default='BSE', max_length=100, verbose_name='AMC Id '),
        ),
    ]
