# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20160912_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Payment_link'),
        ),
    ]
